# https://spacevim.org/cn/documentation
# 所有的 SpaceVim 选项都列在 [options] 之下
[options]
    # 设置 SpaceVim 主题及背景，默认主题模块不加载，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块
    colorscheme = "onedark"
    # 背景可以取值 "dark" 或 "light"
    colorscheme_bg = "dark"
    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以
    # 禁用分割符号，默认为箭头 "arrow"
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 1
    # 显示/隐藏顶部标签栏上的文件类型图标，这一图标需要安装 nerd fonts，
    # 如果未能成功安装这一字体，可以隐藏图标
    enable_tabline_filetype_icon = true
    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    # 字样，只以颜色区分当前模式
    enable_statusline_mode = true
    # 设置文件树在左侧
    filetree_direction = "left"
    # 默认缩进
    default_indent = 4

# -------------------------------------
# SpaceVim 模块设置，主要包括启用/禁用模块

# colorscheme 模块：https://spacevim.org/cn/layers/colorscheme/
[[layers]]
    name = "colorscheme"

# ui 模块：https://spacevim.org/cn/layers/ui/
[[layers]]
    name = "ui"
    enable_sidebar = true
    enable_scrollbar = true
    enable_indentline = false

# autocomplete 模块：https://spacevim.org/cn/layers/autocomplete/
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = "shell"
    default_position = 'top'
    default_height = 30

# -------------------------------------
# SpaceVim 自定义插件

# 自定义主题：https://github.com/EdenEast/nightfox.nvim
# [[custom_plugins]]
#    repo = "EdenEast/nightfox.nvim"
#    merged = 0